version: '3.4'

services:
  db:
    image: mariadb
    command: --bind-address=127.0.0.1 --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    network_mode: host
    volumes:
    - /srv/volumes/mariadb/data:/var/lib/mysql:Z
    - /srv/volumes/mariadb/conf.d/innodb_tweaks.conf:/etc/mysql/conf.d/innodb_tweaks.cnf:ro,Z
    environment:
    - MYSQL_ROOT_PASSWORD=mysql_root_password_here
    - MYSQL_PASSWORD=mysql_genosis_password_here
    - MYSQL_DATABASE=genosis
    - MYSQL_USER=genosis
    - MYSQL_HOST=127.0.0.1
  app:
    image: localhost/stremki/genosis_app:8.1-fpm-alpine3.19
    restart: always
    network_mode: host
    volumes:
    - /srv/volumes/genosis/logs/app:/var/www/data/logs:Z
    - /srv/volumes/genosis/config:/var/www/data/config:Z
    - /srv/volumes/genosis/cache:/var/www/data/cache:Z
    - /srv/volumes/genosis/media:/var/www/data/media:z
    - /srv/volumes/genosis/logs/php:/var/log/php:Z
    # entrypoint: ["tail", "-f", "/dev/null"]
  web:
    image: localhost/stremki/genosis_web:mainline-alpine3.19
    restart: always
    network_mode: host
    depends_on:
    - app
    volumes:
    - /srv/volumes/genosis/media:/var/www/data/media:ro,z
    - /srv/volumes/genosis/nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z
    - /srv/volumes/genosis/logs/nginx:/var/log/nginx:Z
