version: '3.4'

services:
  db:
    image: mariadb
    command: --bind-address=127.0.0.1 --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    network_mode: host
    volumes:
    - /srv/volumes/mariadb/data:/var/lib/mysql:Z
    - /srv/volumes/mariadb/conf.d/innodb_tweaks.conf:/etc/mysql/conf.d/innodb_tweaks.cnf:ro,Z
    environment:
    - MYSQL_ROOT_PASSWORD=your_root_password_here
    - MYSQL_PASSWORD=genosis_user_password_here
    - MYSQL_DATABASE=genosis
    - MYSQL_USER=genosis
    - MYSQL_HOST=127.0.0.1
  app:
    image: php:5-fpm
    restart: always
    network_mode: host
    volumes:
    - /srv/volumes/genosis/app:/var/www:Z
    - /srv/volumes/genosis/config:/var/www/data/config:ro,Z
    - /srv/volumes/genosis/fpm/zz.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro,Z
    - /srv/volumes/genosis/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro,Z
    - /srv/volumes/genosis/fpm/extensions:/usr/local/lib/php/extensions/precompiled:Z
    - /srv/volumes/genosis/fpm/entrypoint.php5.sh:/entrypoint.sh:ro,Z
    - /srv/volumes/genosis/logs/php:/var/log/php:Z
    entrypoint: [ "/entrypoint.sh" ]
  web:
    image: nginx:alpine
    restart: always
    network_mode: host
    volumes:
    - /srv/volumes/genosis/app:/var/www
    - /srv/volumes/genosis/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - /srv/volumes/genosis/logs/nginx:/var/log/nginx:Z
